# Generated by Django 5.2.6 on 2025-09-13 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_book_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('published_date', models.CharField(blank=True, max_length=50)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userbooks', to='core.book'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'book')},
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='google_book_id',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='title',
        ),
    ]
