# Generated by Django 5.2.6 on 2025-09-13 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_alter_userbook_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userbooks', to='core.book'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userbooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
